jobs:

  - job: TestBuildPublish
    pool:
      vmImage: ubuntu-latest

    steps:
    - task: Bash@3
      displayName: 'Base64 decodes and pipes the GPG key content into the secret file'
      env:
        GPG_KEY_CONTENT: $(gpgContent)
        SIGNING_SECRET_KEY_RING_FILE: $(gpgSecretFilePath)
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          sudo bash -c "echo '$GPG_KEY_CONTENT' | base64 -d > '$SIGNING_SECRET_KEY_RING_FILE'"
          ls
    - task: Gradle@2
      displayName: 'gradlew publish to Feed'
      inputs:
        gradleWrapperFile: 'gradlew'
        tasks: 'publishTestFluentUIPublicationToMavenRepository'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '$(jdkVersion)'
        options: '-PGPGSigningKeyID=$(gpgSignKey) -PGPGSigningPassword=$(gpgSignPassword) -PSigningSecretKeyRingFile=$(gpgSecretFileParentPath)'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(build.sourcesdirectory)/build/repo/com/test/fluentui'
        artifact: 'Build'
        publishLocation: 'pipeline'
    
    - task: EsrpRelease@2
      inputs:
        ConnectedServiceName: 'ESRP_Release_Connection'
        Intent: 'PackageDistribution'
        ContentType: 'Maven'
        PackageLocation: '$(build.sourcesdirectory)/build/repo/com/test/fluentui'
        Owners: 'pyeruva@microsoft.com'
        Approvers: 'pyeruva@microsoft.com'
        ServiceEndpointUrl: 'https://api.esrp.microsoft.com'
        MainPublisher: 'fluentuiandroidrelease'
        DomainTenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47'
        