trigger: none
name: $(Date:yyyyMMdd).$(Rev:r)
resources:
  pipelines:
  - pipeline: 'fluentui-android-maven-publish'
    project: 'fluentui-native'
    source: 'fluentui-maven-central-publish [1es-pt]'
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      image: windows-2022
      os: windows
    customBuildTags:
    - ES365AIMigrationTooling-Release
    stages:
    - stage: Stage_1
      displayName: ESRP Release
      jobs:
      - job: Job_1
        displayName: Agent job
        condition: succeeded()
        timeoutInMinutes: 0
        templateContext:
          type: releaseJob
          isProduction: true
          inputs:
          - input: pipelineArtifact
            pipeline: 'fluentui-android-maven-publish'
            artifactName: 'SBom-1'
            targetPath: '$(Pipeline.Workspace)/SBom-1'
          - input: pipelineArtifact
            pipeline: 'fluentui-android-maven-publish'
            artifactName: 'Build'
            targetPath: '$(Pipeline.Workspace)/Build'
          - input: pipelineArtifact
            pipeline: 'fluentui-android-maven-publish'
            artifactName: 'dogfood'
            targetPath: '$(Pipeline.Workspace)/dogfood'
          - input: pipelineArtifact
            pipeline: 'fluentui-android-maven-publish'
            artifactName: 'notes'
            targetPath: '$(Pipeline.Workspace)/notes'
        steps:
        - task: SFP.release-tasks.custom-build-release-task.EsrpRelease@7
          displayName: ESRP Release
          inputs:
            connectedservicename: ESRP_MI_Connection
            keyvaultname: ESRPRelaseCertificates
            authcertname: ESRPAuthCert
            signcertname: '629a43f0-2739-486a-b3e0-e82469a23f80 '
            clientid: 629a43f0-2739-486a-b3e0-e82469a23f80
            folderlocation: $(System.DefaultWorkingDirectory)/fluentui-android-maven-publish/Build
            owners: ronak.dhoot@microsoft.com
            approvers: joypal@microsoft.com
            mainpublisher: fluentuiandroidrelease
    - stage: Stage_2
      displayName: AppCenter Release
      jobs:
      - job: Job_1
        displayName: Agent job
        condition: succeeded()
        timeoutInMinutes: 0
        templateContext:
          inputs:
          - input: pipelineArtifact
            pipeline: 'fluentui-android-maven-publish'
            artifactName: 'SBom-1'
            targetPath: '$(Pipeline.Workspace)/SBom-1'
          - input: pipelineArtifact
            pipeline: 'fluentui-android-maven-publish'
            artifactName: 'Build'
            targetPath: '$(Pipeline.Workspace)/Build'
          - input: pipelineArtifact
            pipeline: 'fluentui-android-maven-publish'
            artifactName: 'dogfood'
            targetPath: '$(Pipeline.Workspace)/dogfood'
          - input: pipelineArtifact
            pipeline: 'fluentui-android-maven-publish'
            artifactName: 'notes'
            targetPath: '$(Pipeline.Workspace)/notes'
        steps:
        - task: AppCenterDistribute@3
          displayName: Deploy $(System.DefaultWorkingDirectory)/fluentui-android-maven-publish/dogfood/FluentUI.Demo-dogfood-release.apk to Visual Studio App Center
          inputs:
            serverEndpoint: App Center Connection Fluent UI
            appSlug: ODSP-UX-Engineering/UI-Fabric
            app: $(System.DefaultWorkingDirectory)/fluentui-android-maven-publish/dogfood/FluentUI.Demo-dogfood-release.apk
            symbolsType: Android
            releaseNotesSelection: file
            releaseNotesFile: $(System.DefaultWorkingDirectory)/fluentui-android-maven-publish/notes/dogfood-release-notes.txt
            isSilent: false