jobs:
  - job: Localize
    pool:
      vmImage: ubuntu-latest

    steps:
    - task: Bash@3
      displayName: Localize
      env:
        TDBUILD_TEAM_ID: $(TDBUILD_TEAM_ID)
        TDBUILD_AAD_APPLICATION_CLIENT_ID: $(TDBUILD_AAD_APPLICATION_CLIENT_ID)
        TDBUILD_AAD_APPLICATION_CLIENT_SECRET: $(TDBUILD_AAD_APPLICATION_CLIENT_SECRET)
      inputs:
        filePath: './localize.sh'
      
    - task: Bash@3
      displayName: Create PR
      inputs:
        targetType: 'inline'
        script: |
          echo "Start."
          # Configure git and Push updates
          git config --global user.email pyeruva@microsoft.com
          git config --global user.name PraveenKumar Yeruva
          git config pull.rebase false
          branch=localization-update-$(date +"%s")

          checkout -b $branch
          message='Automated documentation update'
          # Add / update and commit
          git add .
          git commit -m 'Test Localization [skip ci]' || export NO_UPDATES=true
          # Push
          if [ "$NO_UPDATES" != "true" ] ; then
          git push origin "$branch"
          gh pr create --title "Localization from TDBuild" --body "Updated strings"