jobs:
  - job: Localize
    pool:
      vmImage: ubuntu-latest

    steps:
    - task: Bash@3
      displayName: Localize
      env:
        TDBUILD_TEAM_ID: $(TDBUILD_TEAM_ID)
        TDBUILD_AAD_APPLICATION_CLIENT_ID: $(TDBUILD_AAD_APPLICATION_CLIENT_ID)
        TDBUILD_AAD_APPLICATION_CLIENT_SECRET: $(TDBUILD_AAD_APPLICATION_CLIENT_SECRET)
      inputs:
        targetType: 'inline'
        script: |
            touch test.txt
      
    - task: Bash@3
      displayName: Create PR
      inputs:
        targetType: 'inline'
        script: |
            set -e
            echo "Start."
            # Configure git and Push updates
            git config --global user.email pyeruva@microsoft.com
            git config --global user.name PraveenKumar Yeruva
            git config pull.rebase false
            branch=testLocalize-$(date +%s)
            git branch $branch origin/master
            git checkout $branch
            # Add / update and commit
            git add .
            git status | grep modified
            if [ $? -eq 0 ]
            then
                git commit -m 'Test Localization [skip ci]'
                git push origin $branch
                gh pr create --title "Test PR" --body "Updated Test strings"
            else
                echo "No changes since last run"
            fi