package microsoft.fluentui.generator

const val ATTRIBUTE_PREFIX = "fluentUI_"
const val ANIMATOR_PREFIX = "AN_"
const val AP_PREFIX = "AP_"
const val EXTENSION_TAG = " extends "
const val AUTOGENERATED_MESSAGE = "Auto-generated code, all changes will be lost"
const val AUTOGENERATED_CODE_HEADER = "/**\n * $AUTOGENERATED_MESSAGE\n */\n"
const val AUTOGENERATED_XML_HEADER = "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n\n<!-- $AUTOGENERATED_MESSAGE -->\n\n"
const val NEW_LINE = "\n\n"
const val OPEN_VAL_PREFIX = "\t open var "
const val OVERRIDE_VAL_PREFIX = "\t override var "