package com.msft.stardust

import java.io.File

// Deletes all autogenerated files

fun starduster() {
    File("${global_projectRoot}/generatedSrc").deleteRecursively()
    println("> Deleted generatedSrc folder")
}
