name: FluentUI Android Demo APK Release

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag (e.g., v0.3.8)'
        required: true
        type: string
      release_name:
        description: 'Release name (e.g., FluentUI Android Demo v0.3.8)'
        required: true
        type: string
      prerelease:
        description: 'Mark as pre-release'
        required: false
        type: boolean
        default: false

permissions:
  contents: write
  actions: read

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Create keystore directory
      run: mkdir -p FluentUI.Demo

    - name: Decode and create keystore
      env:
        KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
      run: |
        if [ -n "$KEYSTORE_BASE64" ]; then
          echo "$KEYSTORE_BASE64" | base64 -d > FluentUI.Demo/keystore.jks
        else
          echo "Warning: KEYSTORE_BASE64 secret not found. Creating dummy keystore for build."
          keytool -genkey -v -keystore FluentUI.Demo/keystore.jks -alias Dogfood -keyalg RSA -keysize 2048 -validity 10000 -storepass android -keypass android -dname "CN=Test, OU=Test, O=Test, L=Test, S=Test, C=US"
        fi

    - name: Build dogfood release APK
      env:
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        SIGNING_KEYSTORE_PASSWORD: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
      run: |
        ./gradlew :FluentUI.Demo:assembleDogfoodRelease \
          -PsigningKeyPassword="${SIGNING_KEY_PASSWORD:-android}" \
          -PsigningKeyStorePassword="${SIGNING_KEYSTORE_PASSWORD:-android}"

    - name: Verify APK exists
      run: |
        APK_PATH="FluentUI.Demo/build/outputs/apk/dogfood/release/FluentUI.Demo-dogfood-release.apk"
        if [ -f "$APK_PATH" ]; then
          echo "APK found at: $APK_PATH"
          ls -la "$APK_PATH"
        else
          echo "APK not found at expected location: $APK_PATH"
          echo "Searching for APK files:"
          find FluentUI.Demo/build -name "*.apk" -type f
          exit 1
        fi

    - name: Read release notes
      id: release_notes
      run: |
        NOTES_FILE="FluentUI.Demo/src/main/assets/dogfood-release-notes.txt"
        if [ -f "$NOTES_FILE" ]; then
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_OUTPUT
          cat "$NOTES_FILE" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        else
          echo "RELEASE_NOTES=No release notes available." >> $GITHUB_OUTPUT
        fi

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.release_tag }}
        release_name: ${{ github.event.inputs.release_name }}
        body: |
          # FluentUI Android Demo Release

          ${{ steps.release_notes.outputs.RELEASE_NOTES }}

          ## Installation
          Download the APK file below and install it on your Android device.

          **Note**: This is a dogfood build for testing purposes.
        draft: false
        prerelease: ${{ github.event.inputs.prerelease }}

    - name: Upload APK to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: FluentUI.Demo/build/outputs/apk/dogfood/release/FluentUI.Demo-dogfood-release.apk
        asset_name: FluentUI.Demo-dogfood-release.apk
        asset_content_type: application/vnd.android.package-archive

    - name: Output release information
      run: |
        echo "✅ Release created successfully!"
        echo "🔗 Release URL: ${{ steps.create_release.outputs.html_url }}"
        echo "📱 APK uploaded as release asset"