on: workflow_dispatch

jobs:
  Localize:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - shell: bash
      name: Localize
      env:
        TDBUILD_TEAM_ID: ${{ secrets.TDBUILD_TEAM_ID }}
        TDBUILD_AAD_APPLICATION_CLIENT_ID: ${{ secrets.TDBUILD_AAD_APPLICATION_CLIENT_ID }}
        TDBUILD_AAD_APPLICATION_CLIENT_SECRET: ${{ secrets.TDBUILD_AAD_APPLICATION_CLIENT_SECRET }}
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      run: ./localize.sh
    - name: Create Pull Request
      run: |
        set -e
        echo "Start."
        # Configure git and Push updates
        git config --global user.email pyeruva@microsoft.com
        git config --global user.name PraveenKumar Yeruva
        git config pull.rebase false
        branch=testLocalize-$GITHUB_RUN_ID
        message='Testing localization'
        git branch
        echo "Creating branch $branch"
        git branch $branch
        echo "Checkout $branch"
        git checkout $branch
        # Add / update and commit
        git status
        echo "adding files"
        git add .
        if [[ `git status --porcelain` ]]; then
            echo "Adding git commit"
            git commit -m 'Test Localization [skip ci]'
            echo "Pushing to origin"
            git push origin HEAD
            echo "Creating PR"
            gh api \
                --method POST \
                -H "Accept: application/vnd.github+json" \
                /repos/${GITHUB_REPOSITORY}/pulls \
                -f title="$message" \
              -f body="$message" \
              -f head="$branch" \
              -f base='main'
        else
            echo "No changes since last run"
        fi
